
openapi: "3.0.0"

info:
  title: Test Schema
  description: API to illustrate OpenAPI-SQLALchemy MVP.
  version: "0.1"

paths:
  /employee:
    get:
      summary: Used to retrieve all employees.
      responses:
        200:
          description: Return all employees from the database.
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Employee"

components:
  schemas:
    Id:
      type: integer
      description: Unique identifier for the employee.
      example: 0
      x-primary-key: true
      x-autoincrement: true
    Name:
      type: string
      description: The name of the employee.
      example: David Andersson.
      x-index: true
    Division:
      type: string
      description: The part of the company the employee works in.
      example: Engineering
      x-index: true
    Salary:
      type: number
      description: The amount of money the employee is paid.
      example: 1000000.00
    Employee:
      description: Person that works for a company.
      type: object
      x-tablename: employee
      properties:
        id:
          $ref: "#/components/schemas/Id"
        name:
          $ref: "#/components/schemas/Name"
        division:
          $ref: "#/components/schemas/Division"
        salary:
          $ref: "#/components/schemas/Salary"
      required:
        - id
        - name
        - division
